### ISSUE TITLE
Super Minor Formatting related to the new rent/rented acres and owed/owned acres

### ISSUE THREAD

**Issue by KelleyDrake** [ddrake/Integrated_Farm_Budget_Tool#106] opened 2023-07-15 00:23 UTC
The current formatting beneath the detailed budget tab is shoving the $/acre columns off to the right.   I worry if we have 4 crops we might need that space and it looks a little weird as it is now.   Wondering if the formating could be adjusted or alternatively if perhaps the new rent/rented acre, owned/owned acre can be set off into its own separate section below the detailed budget and lined up under the correct columns.   Take a look at the Wood County Farm and you'll see what I'm talking about.  If it is hard to fix, no big deal though.  Just minor formatting comment.

**Comment by ddrake** [comment] 2023-07-15 15:15
I agree that it looks a bit weird in the cases of one or two crops.  If I were to move it to its own div completely below the detailed budget, it could be wider than the $/acre column and wouldn't affect its width, but then I would have no way to align it with respect to that column.  

As it is, the problem is that the text descriptions are longer than the columns, which contain only numbers.  But they are set to span as many columns as possible so that in cases of 3 or 4 crops, the $/acre budget column is actualy widened less than in the 2-crop case.

**Comment by ddrake** [comment] 2023-07-15 15:18
Closing as complete for now, but we can certainly revisit the formatting of the detailed budget at some points, e.g. to add blank lines and cell borders above totals, etc...

**Closed as completed by ddrake** 2023-07-15 15:18 UTC
